name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get && dart run build_runner build
      - name: Verify formatting and analyze
        run: |
          dart format --set-exit-if-changed .
          dart analyze
      - name: Run tests
        run: flutter test
      - name: Build APK
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: flutter build apk --dart-define API_KEY=$API_KEY
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk